services:
  windows:
    image: dockurr/windows
    container_name: codespace-windows

    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "20G"
      AUDIO: "Y"
      NETWORK: "user"

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/kvm
      - /dev/net/tun

    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"

    volumes:
      - ./windows:/storage
      - ./shared:/shared

    stop_grace_period: 2m
    restart: unless-stopped
