services:
  windows:
    image: dockurr/windows
    container_name: codespace-windows
    network_mode: host

    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
      AUDIO: "Y"

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/kvm
      - /dev/net/tun

    volumes:
      - ./windows:/storage
      - ./shared:/shared

    stop_grace_period: 2m
    restart: unless-stopped
